# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='authentication_method',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Create Super User'), (1, 'Back end'), (2, 'Proprietary')], default=1, verbose_name='Authentication method'),
        ),
    ]
