# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 16:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenta', '0003_auto_20170705_1610'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='dateupdate',
            new_name='date_update',
        ),
    ]
