# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-08 18:22
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenta', '0005_auto_20170807_1625'),
    ]

    operations = [
        migrations.CreateModel(
            name='Method',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ldap_host', models.CharField(blank=True, help_text='Hostname/IP', max_length=254, null=True, verbose_name='Use hostname or IP address')),
                ('ldap_port', models.PositiveIntegerField(blank=True, default=389, help_text='Keep 389 to use default port', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(65535)], verbose_name='Port')),
                ('ldap_tls', models.BooleanField(default=False, help_text='Use option TLS', verbose_name='Option TLS')),
                ('ldap_cacert', models.FileField(blank=True, help_text='Uploade here the certificat to check', null=True, upload_to='ldapcerts', verbose_name='Certificat LDAP')),
                ('ldap_define', models.CharField(blank=True, help_text='Base DN', max_length=254, null=True, verbose_name='Base DN ex: dc=domain,dc=com')),
                ('ldap_scope', models.CharField(choices=[('SCOPE_BASE', 'SCOPE_BASE'), ('SCOPE_ONELEVEL', 'SCOPE_ONELEVEL'), ('SCOPE_SUBTREE', 'SCOPE_SUBTREE')], default='SCOPE_BASE', help_text='Choice a scope', max_length=14, verbose_name='Scope')),
                ('ldap_version', models.CharField(choices=[('VERSION2', 'VERSION2'), ('VERSION3', 'VERSION3')], default='VERSION2', help_text='Choice a version', max_length=8, verbose_name='Choice a version')),
                ('ldap_bind', models.CharField(blank=True, help_text='Bind for override user permission, ex: cn=manager,dc=domain,dc=com (Keep null if not used)', max_length=254, null=True, verbose_name='Bind DN')),
                ('ldap_password', models.CharField(blank=True, help_text='Password used by the bind', max_length=254, null=True, verbose_name='Password')),
                ('ldap_user', models.TextField(blank=True, help_text='Replace Bind DN by a User DN. <strong>Do not use with Bind DN</strong> | user DN ex : uid={{username}},ou=my-ou,dc=domain,dc=com | Available tags: {{username}}', null=True, verbose_name='User DN')),
                ('ldap_search', models.TextField(blank=True, help_text='search DN (ldap filter) ex : (&(uid={{username}})(memberof=cn=my-cn,ou=groups,dc=hub-t,dc=net)) | Available tags: {{username}}', null=True, verbose_name='Search DN')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='authentication_method',
            field=models.CharField(choices=[('CREATESUPERUSER', 'Create Super User'), ('BACKEND', 'Back-end'), ('FRONTEND', 'Front-end')], default='FRONTEND', max_length=15, verbose_name='Authentication method'),
        ),
    ]
