# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenta', '0005_auto_20170705_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='authentication_method',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Create Super User'), (1, 'Back-end'), (2, 'Front-end')], default=2, verbose_name='Authentication method'),
        ),
    ]
