# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenta', '0006_auto_20170705_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='update_by',
            field=models.CharField(max_length=254, null=True, verbose_name='Update by'),
        ),
    ]
