# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenta', '0007_user_update_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='update_by',
            field=models.CharField(editable=False, max_length=254, null=True, verbose_name='Update by'),
        ),
    ]
