# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-08 21:12
from __future__ import unicode_literals

import authenta.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenta', '0007_auto_20170808_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='method',
            name='name',
            field=models.CharField(default='test', help_text='Naming your authentication', max_length=254, verbose_name='Authentication Name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='method',
            name='ldap_cacert',
            field=models.FileField(blank=True, help_text='Uploade here the certificat to check', null=True, upload_to=authenta.models.ldap_certsdir, verbose_name='Certificat LDAP'),
        ),
        migrations.AlterField(
            model_name='method',
            name='method',
            field=models.CharField(choices=[('LDAP', 'ldap')], default='LDAP', help_text='Authentication type', max_length=4, verbose_name='Method'),
        ),
    ]
