# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-27 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenta', '0009_auto_20170727_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Active'),
        ),
    ]
