# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-08 21:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenta', '0009_auto_20170808_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='method',
            name='status',
            field=models.BooleanField(default=True, help_text='Authentication enable or disable', verbose_name='Activated'),
        ),
    ]
