# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-08 21:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenta', '0010_method_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='method',
            name='error',
            field=models.TextField(blank=True, editable=False, null=True, verbose_name='Error encountered'),
        ),
        migrations.AlterField(
            model_name='method',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='method',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='Staff'),
        ),
        migrations.AlterField(
            model_name='method',
            name='is_superuser',
            field=models.BooleanField(default=False, verbose_name='Superuser'),
        ),
    ]
