# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-27 19:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenta', '0011_auto_20170727_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='Staff'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Last name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='update_by',
            field=models.CharField(editable=False, max_length=254, verbose_name='Update by'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='Username'),
        ),
    ]
